version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo1234
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  gateway:
    depends_on:
      - mongodb
    build: ./gateway
    restart: unless-stopped
    # env_file:
    #   - ./gateway/.env
    ports:
      - 3000:3000
    environment:
      # docker-compose에서 host는 서비스명 입력
      # authSource: 'root' 사용자로 인증하여 접속
      - MONGODB=mongodb://mongo:mongo1234@mongodb:27017/express?authSource=admin
    #컨테이너에 접근옵션
    stdin_open: true
    tty: true

  board:
    build: ./board
    restart: unless-stopped
    # env_file:
    #   - ./board/.env
    ports:
      - 3001:3001
    #컨테이너에 접근옵션
    stdin_open: true
    tty: true

volumes:
  db:
