version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo1234
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  gateway:
    depends_on:
      - mongodb
    build: ./gateway
    restart: unless-stopped
    env_file: ./gateway/.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=mongo
      - DB_PASSWORD=mongo1234
      - DB_NAME=express
      - DB_PORT=27017
    stdin_open: true
    tty: true

volumes:
  db:
