version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo1234
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - node-network

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    # 헬스 체크
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: express
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    networks:
      - node-network

  gateway:
    depends_on:
      - mongodb
    build: ./gateway
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      # docker-compose에서 host는 서비스명 입력
      # authSource: 'root' 사용자로 인증하여 접속
      - MONGODB=mongodb://mongo:mongo1234@mongodb:27017/express?authSource=admin
      - BOARD_HOST=board:3001
    networks:
      - node-network
    #터미널에서 컨테이너 접근옵션
    stdin_open: true
    tty: true

  board:
    depends_on:
      postgres:
        # 헬스체크 확인 후 실행
        condition: service_healthy
    build: ./board
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - DB_HOST=postgres
    networks:
      - node-network
    volumes:
      - "./board/src/db/init/:/docker-entrypoint-initdb.d/"
    #터미널에서 컨테이너 접근옵션
    stdin_open: true
    tty: true

volumes:
  db:
networks:
  node-network:
    driver: bridge
